language: go
go_import_path: github.com/kevinburke/go-types

os: linux
dist: trusty

sudo: required

before_script:
     - wget "https://storage.googleapis.com/bazel-apt/pool/jdk1.8/b/bazel/bazel_0.5.3_amd64.deb"
     - sudo dpkg --force-all -i bazel_0.5.3_amd64.deb

script:
  - make ci
